export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";

export const PRODUCT_GET_REQUEST = "PRODUCT_GET_REQUEST";
export const PRODUCT_GET_SUCCESS = "PRODUCT_GET_SUCCESS";
export const PRODUCT_GET_FAIL = "PRODUCT_GET_FAIL";

export const PRODUCT_SINGLE_REQUEST = "PRODUCT_SINGLE_REQUEST";
export const PRODUCT_SINGLE_SUCCESS = "PRODUCT_SINGLE_SUCCESS";
export const PRODUCT_SINGLE_FAIL = "PRODUCT_SINGLE_FAIL";
